### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by cyclinder** [spidernet-io/cilium-chaining#1]
- [x] add helm chart
- [x] a simple e2e: test the installtion
- [x] docs: how to use it
- [ ] docs: how to enable hubble
- [ ] docs: how to use network policy
- [ ] docs: how to work with ipvlan and spiderpool
